# This is a basic workflow to help you get started with Actions

name: nginx web

on:

  push:
    branches: [ "master" ]


  workflow_dispatch:

env:
  DOCKER_REPO: jx-cloud/my-nginx
  IMAGE_TAG: v2
jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v4

      - name: docker/build-push-action
        run: docker build -t swr.cn-north-4.myhuaweicloud.com/${DOCKER_REPO}:${IMAGE_TAG} .
      # Runs login swr
      #- name: docker/login-action@v3
       # with:
      ##    username: cn-north-4@HPUAPZ498EOIYCXORR4X
       #   password: ${{ secrets.MY_SRW_SK }}
      - name: docker login v1 
        run: docker login -u cn-north-4@HPUAPZ498EOIYCXORR4X -p ${{ secrets.MY_SWR_SK }}  swr.cn-north-4.myhuaweicloud.com
      # Runs a set of commands using the runners shell
      - name: docker push 
        run: docker push swr.cn-north-4.myhuaweicloud.com/${DOCKER_REPO}:${IMAGE_TAG}   


